title: Minglei Chen's Homepage
page-top-title: Minglei Chen
top-section-bg-text: 保持谦虚&ensp;|&ensp;不断学习
home-subtitle: Minglei Chen&ensp;|&ensp;陈明磊
copyright-text: '&copy; Minglei Chen 2023-2025. All Rights Reserved.'
